# ============================================================================ #
# Copyright (c) 2022 - 2026 NVIDIA Corporation & Affiliates.                   #
# All rights reserved.                                                         #
#                                                                              #
# This source code and the accompanying materials are made available under     #
# the terms of the Apache License 2.0 which accompanies this distribution.     #
# ============================================================================ #
"""Propagator computation for the CUDA-Q ``dynamics`` backend.

Compute the propagator of a (possibly time-dependent) Hamiltonian via
time-ordered exponential, analogous to QuTiP's ``propagator``, on the
``dynamics`` target.

Closed system
    The propagator ``U(t)`` is the unitary satisfying

        dU/dt = -i H(t) U(t),    U(0) = I,

    obtained by encoding the right-hand side as a ``cudaq.SuperOperator``
    left-multiplication and evolving the identity density matrix.

Open system (``collapse_operators`` given)
    The propagator is the dynamical map ``Phi(t)`` (a ``d^2 x d^2``
    superoperator) generated by the Lindbladian

        d(rho)/dt = -i[H, rho] + sum_k ( c_k rho c_k^dag
                                         - 1/2 {c_k^dag c_k, rho} ).

    ``Phi(t)`` is assembled column-by-column by evolving the ``d^2`` basis
    density matrices |m><n| (the columns of the identity superoperator) and
    stacking the vectorized results.

Note:
    The ``dynamics`` target requires an NVIDIA GPU (cuQuantum / cuDensityMat);
    there is no CPU code path. Items tagged ``TODO(gpu)`` / ``TODO(api)`` must be
    confirmed on hardware.
"""

from __future__ import annotations

from typing import Mapping, Optional, Sequence

import numpy as np

__all__ = ["propagator"]


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def _total_dimension(dimensions: Mapping[int, int]) -> int:
    """Product of the per-degree Hilbert-space dimensions."""
    dim = 1
    for d in dimensions.values():
        dim *= d
    return dim


def _identity_state(dim: int):
    """U(0) = I initial condition, as a ``dim x dim`` density-matrix-shaped state.

    ``State.from_data`` accepts a 2-D ``dim x dim`` array (cf.
    ``test_evolve_dynamics.py:241`` where a 2-D density matrix round-trips), so
    no manual flattening is needed.
    """
    import cudaq

    return cudaq.State.from_data(np.eye(dim, dtype=np.complex128))


def _state_to_matrix(state, dim: int) -> np.ndarray:
    """Extract an evolved dynamics state as a ``dim x dim`` complex matrix.

    ``np.array(state)`` is the confirmed extraction idiom and returns the 2-D
    matrix directly (``test_evolve_dynamics.py:241``). The 1-D branch is a
    defensive fallback only.
    """
    arr = np.asarray(np.array(state), dtype=np.complex128)
    if arr.ndim == 1:  # TODO(gpu): defensive — confirm states come back 2-D
        arr = arr.reshape(dim, dim)
    return arr


def _dagger(operator):
    """Hermitian conjugate (``c^dag``) of a collapse operator.

    TODO(api): confirm the operator-adjoint API in CUDA-Q. No Python
    ``.dagger()``/``.adjoint()`` is surfaced in ``python/cudaq/operators`` (the
    dynamics tests build daggers by hand, e.g. ``annihilate`` <-> ``create``),
    though ``complex_matrix.adjoint()`` exists at the C++ level
    (``runtime/cudaq/operators/matrix.cpp:422``). On hardware, introspect a
    bound operator (``dir(op)``) for an adjoint/conjugate method; failing that,
    build it from ``op.to_matrix(dimensions)`` -> conjugate-transpose -> a custom
    operator.
    """
    for name in ("dagger", "adjoint", "conjugate"):
        method = getattr(operator, name, None)
        if callable(method):
            return method()
    raise NotImplementedError(
        "Cannot take the adjoint of a collapse operator: no dagger/adjoint "
        "method found on the operator. Resolve the CUDA-Q operator adjoint API "
        "(see TODO(api) in _dagger) before using the open-system path.")


def _lindblad_super_op(hamiltonian, collapse_operators):
    """Build the Lindbladian ``L`` as a ``cudaq.SuperOperator``.

    Mirrors the master-equation construction in
    ``python/tests/dynamics/system_models.py:586-598``: the unitary part
    ``-i[H, rho]`` plus, for each collapse operator ``c``, the dissipator
    ``c rho c^dag - 1/2 {c^dag c, rho}``.
    """
    import cudaq

    super_op = cudaq.SuperOperator()
    # Unitary part: -i[H, rho] = -i H rho + i rho H
    super_op += cudaq.SuperOperator.left_multiply(-1j * hamiltonian)
    super_op += cudaq.SuperOperator.right_multiply(1j * hamiltonian)
    for c in collapse_operators:
        c_dag = _dagger(c)
        # c rho c^dag
        super_op += cudaq.SuperOperator.left_right_multiply(c, c_dag)
        # -1/2 c^dag c rho   and   -1/2 rho c^dag c
        super_op += cudaq.SuperOperator.left_multiply(-0.5 * c_dag * c)
        super_op += cudaq.SuperOperator.right_multiply(-0.5 * c_dag * c)
    return super_op


def _assemble_dynamical_map(results, d2: int, store_intermediate: bool):
    """Stack evolved basis states into the ``d^2 x d^2`` dynamical map(s).

    ``results[j]`` is the evolution of the j-th basis density matrix. Column j
    of ``Phi`` is ``vec`` of that evolved matrix. We vectorize row-major (C
    order) to match the basis ordering ``j = m*dim + n`` used in
    ``_open_system_map``; ``Phi`` therefore acts on row-major ``vec(rho)``.
    TODO(gpu): confirm this convention against ``qutip.propagator`` by comparing
    the *action* on a test ``rho`` rather than the raw matrices.
    """
    if store_intermediate:
        num_steps = len(results[0].intermediate_states())
        maps = []
        for s in range(num_steps):
            cols = [
                np.array(results[j].intermediate_states()[s]).reshape(-1)
                for j in range(d2)
            ]
            maps.append(np.stack(cols, axis=1))
        return maps
    cols = [np.array(results[j].final_state()).reshape(-1) for j in range(d2)]
    return np.stack(cols, axis=1)


def _open_system_map(hamiltonian, dimensions, schedule, collapse_operators,
                     integrator, store_intermediate_results, max_batch_size,
                     dim):
    """Dynamical map ``Phi(t)`` for one Hamiltonian (``d^2`` batched evolutions).

    Note: this costs ``d^2`` trajectories; it grows quickly with the total
    Hilbert-space dimension.
    """
    import cudaq

    d2 = dim * dim
    lindbladian = _lindblad_super_op(hamiltonian, collapse_operators)

    # Columns of the identity superoperator: basis density matrices E_{mn} =
    # |m><n|, ordered j = m*dim + n.
    basis_states = []
    for j in range(d2):
        e = np.zeros((dim, dim), dtype=np.complex128)
        e[j // dim, j % dim] = 1.0
        basis_states.append(cudaq.State.from_data(e))

    save_mode = (cudaq.IntermediateResultSave.ALL
                 if store_intermediate_results else
                 cudaq.IntermediateResultSave.NONE)

    results = cudaq.evolve(
        lindbladian,
        dimensions,
        schedule,
        basis_states,  # single super-op broadcast over d^2 initial states
        collapse_operators=[],  # already folded into the SuperOperator
        store_intermediate_results=save_mode,
        integrator=integrator,
        max_batch_size=max_batch_size,
    )
    return _assemble_dynamical_map(results, d2, store_intermediate_results)


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #
def propagator(
    hamiltonian,
    dimensions: Mapping[int, int],
    schedule,
    *,
    collapse_operators: Sequence = (),
    integrator=None,
    store_intermediate_results: bool = False,
    max_batch_size: Optional[int] = None,
):
    """Compute the propagator of a Hamiltonian on the dynamics backend.

    Analogous to QuTiP's ``propagator``. Integrates over the times in
    ``schedule`` using the ``dynamics`` target.

    Args:
        hamiltonian: A CUDA-Q ``Operator``, or a sequence of operators to
            compute a batch of propagators (e.g. a parameter sweep) in one call.
        dimensions: Mapping from degree-of-freedom index to Hilbert-space
            dimension, e.g. ``{0: 2}`` for a single qubit.
        schedule: A ``cudaq.Schedule`` of time points at which to evaluate the
            propagator.
        collapse_operators: Optional Lindblad collapse operators. When provided,
            the result is the open-system dynamical map -- a ``d^2 x d^2``
            ``numpy.ndarray`` acting on row-major ``vec(rho)`` -- instead of a
            unitary.
        integrator: Optional ``BaseIntegrator``; defaults to the backend default.
        store_intermediate_results: If True, return the propagator at every step
            of the schedule; otherwise return only the value at the final time.
        max_batch_size: Optional cap on the batch size handled at once.

    Returns:
        Closed system: the unitary ``U`` as a ``dim x dim`` complex
        ``numpy.ndarray``. Open system: the dynamical map as a ``d^2 x d^2``
        array. With ``store_intermediate_results`` a list over the schedule;
        with a batched ``hamiltonian`` a list over the batch (outermost).

    Note:
        Requires the ``dynamics`` target and an NVIDIA GPU.
    """
    import cudaq  # deferred import: avoid a circular import at package load

    dim = _total_dimension(dimensions)
    is_batched = isinstance(hamiltonian, (list, tuple))
    hamiltonians = list(hamiltonian) if is_batched else [hamiltonian]

    # ----- Open system: one dynamical map per Hamiltonian ----------------- #
    if len(collapse_operators) > 0:
        # TODO(perf): the batch loop runs d^2 evolutions per Hamiltonian
        # sequentially. These could be flattened into a single evolve() call
        # (a list of (num_batch * d^2) super-ops + matching basis states) once
        # the single-Hamiltonian path is validated.
        maps = [
            _open_system_map(h, dimensions, schedule, collapse_operators,
                             integrator, store_intermediate_results,
                             max_batch_size, dim) for h in hamiltonians
        ]
        return maps if is_batched else maps[0]

    # ----- Closed system: unitary propagator(s) --------------------------- #
    super_ops = []
    for h in hamiltonians:
        super_op = cudaq.SuperOperator()
        # dU/dt = -i H(t) U  ->  left-multiplication only (no commutator term).
        super_op += cudaq.SuperOperator.left_multiply(-1j * h)
        super_ops.append(super_op)

    initial_states = [_identity_state(dim) for _ in super_ops]
    save_mode = (cudaq.IntermediateResultSave.ALL
                 if store_intermediate_results else
                 cudaq.IntermediateResultSave.NONE)

    results = cudaq.evolve(
        super_ops if is_batched else super_ops[0],
        dimensions,
        schedule,
        initial_states if is_batched else initial_states[0],
        collapse_operators=[],  # SuperOperator path forbids separate collapse ops
        store_intermediate_results=save_mode,
        integrator=integrator,
        max_batch_size=max_batch_size,
    )

    def _extract(result):
        if store_intermediate_results:
            return [
                _state_to_matrix(s, dim) for s in result.intermediate_states()
            ]
        return _state_to_matrix(result.final_state(), dim)

    if is_batched:
        return [_extract(r) for r in results]
    return _extract(results)
